In [ ]:
pip install pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn import preprocessing


In [3]:

# Load your dataset
data = pd.read_csv('iris.csv')
data.head()


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
data.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [5]:
data.info

<bound method DataFrame.info of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-seto

In [6]:
data.nunique

<bound method DataFrame.nunique of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-s

In [7]:
data.describe

<bound method NDFrame.describe of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-se

In [8]:
# Use 'Species' column for label encoding
le = preprocessing.LabelEncoder()
le.fit(list(data['Species'].unique()))
data['Numeric_species'] = le.transform(list(data['Species'].values))

X1 = data.iloc[:, data.columns != 'Species']
X = X1.iloc[:, X1.columns != 'Numeric_species']
Y = data['Numeric_species']

# Initialize weights based on the number of features
B = np.zeros(X.shape[1])
alpha = 0.1



In [9]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def net_input(B, x):
    return np.dot(x, B)

def cost_function(h, y):
    epsilon = 1e-15  # A small constant to avoid log(0)
    h = np.clip(h, epsilon, 1 - epsilon)  # Clip predicted probabilities to avoid extremes
    return (-y * np.log(h) - (1 - y) * np.log(1 - h)).mean()

m = len(Y)
epochs = 100




In [10]:
for iteration in range(epochs):
    z = net_input(B, X)
    h = sigmoid(z)
    gradient = np.dot(X.T, (h - Y)) / m
    B1 = alpha * gradient
    B = B - B1
    cost = cost_function(h, Y)
    print (B,cost)

[7.10833333 0.3449     0.1379     0.3242     0.11933333] 0.6931471805599454
[10.4416667   0.39763352  0.12310013  0.46046672  0.17873334] -0.37829141079287637
[13.77500004  0.45036685  0.10830013  0.59673338  0.23813334] -0.21269697366274462
[17.10833337  0.50310019  0.09350013  0.73300005  0.29753334] -0.13855285384624647
[20.4416667   0.55583352  0.07870013  0.86926672  0.35693334] -0.08968316314942967
[23.77500004  0.60856685  0.06390013  1.00553338  0.41633334] -0.06466228619154207
[27.10833337  0.66130019  0.04910013  1.14180005  0.47573334] -0.03964001448687365
[30.4416667   0.71403352  0.03430013  1.27806672  0.53513334] -0.014565347048916617
[3.37750000e+01 7.66766855e-01 1.95001290e-02 1.41433338e+00
 5.94533341e-01] 3.031649005909761e-15
[3.71083334e+01 8.19500188e-01 4.70012897e-03 1.55060005e+00
 6.53933341e-01] 3.031649005909761e-15
[ 4.04416667e+01  8.72233521e-01 -1.00998710e-02  1.68686672e+00
  7.13333341e-01] 3.031649005909761e-15
[ 4.37750000e+01  9.24966855e-01 -2.4

In [11]:
z= X.dot(B)
h = sigmoid(z)

In [12]:
print(z,h)

0        381.387262
1        718.046145
2       1052.394458
3       1391.841891
4       1729.131315
           ...     
145    49336.759391
146    49667.142281
147    50008.062977
148    50347.533641
149    50676.358897
Length: 150, dtype: float64 0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ... 
145    1.0
146    1.0
147    1.0
148    1.0
149    1.0
Length: 150, dtype: float64
